name: Build and Upload Artifacts

on:
  release:
    types: [published]  # Trigger this workflow when a release is published

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]  # Build for multiple platforms

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build application
      run: |
        python scripts/build.py
        mkdir -p "dist-${{ matrix.os }}"
        mv dist/* "dist-${{ matrix.os }}/"

    - name: Zip the build artifacts
      run: |
        zip -r "dist-${{ matrix.os }}.zip" "dist-${{ matrix.os }}/"

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: "dist-${{ matrix.os }}.zip"
        path: "dist-${{ matrix.os }}.zip"

  upload:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: dist-ubuntu-latest.zip
        path: dist-ubuntu-latest.zip

    - name: Download build artifacts macOS
      uses: actions/download-artifact@v4
      with:
        name: dist-macos-latest.zip
        path: dist-macos-latest.zip

    - name: Download build artifacts Windows
      uses: actions/download-artifact@v4
      with:
        name: dist-windows-latest.zip
        path: dist-windows-latest.zip

    - name: Upload Release Assets for Ubuntu
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: dist-ubuntu-latest.zip
        asset_name: dist-ubuntu-latest.zip
        asset_content_type: application/zip

    - name: Upload Release Assets for macOS
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: dist-macos-latest.zip
        asset_name: dist-macos-latest.zip
        asset_content_type: application/zip

    - name: Upload Release Assets for Windows
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: dist-windows-latest.zip
        asset_name: dist-windows-latest.zip
        asset_content_type: application/zip

