name: Build and Upload Artifacts

on:
  release:
    types: [published]  # Trigger this workflow when a release is published

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]  # Build for multiple platforms

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build application
      run: |
        python scripts/build.py
        mkdir -p "dist-${{ matrix.os }}"
        mv dist/* "dist-${{ matrix.os }}/"

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: "dist-${{ matrix.os }}"
        path: "dist-${{ matrix.os }}/"


  upload:
    needs: build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]  # Use the same platforms

    steps:
    - name: Download build artifact
      uses: actions/download-artifact@v4
      with:
        name: "dist-${{ matrix.os }}"
        path: "dist-${{ matrix.os }}/"

    - name: Zip build artifact
      run: |
        zip -r "dist-${{ matrix.os }}.zip" "dist-${{ matrix.os }}/"

    - name: Upload Release Assets
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: "dist-${{ matrix.os }}.zip"
        asset_name: "dist-${{ matrix.os }}.zip"
        asset_content_type: application/zip

